### ISSUE TITLE
Whether to support non-numeric variables

### ISSUE THREAD

**Issue by 630362055** [SimonBlanke/Gradient-Free-Optimizers#16]
![image](https://user-images.githubusercontent.com/25970108/132240837-ffc3be14-59f3-4f33-b23b-ecef3f16672e.png)
![image](https://user-images.githubusercontent.com/25970108/132240886-f7f4b6b6-a38c-439f-83a6-2da7a5e005b2.png)

**Comment by 630362055** [comment]
if i want to optimize string variable, how to do that

**Comment by SimonBlanke** [comment]
Gradient-Free-Optimizers will not support string variables in the search space in the future, because I want to keep it simple.
For these more complex search spaces I created [Hyperactive](https://github.com/SimonBlanke/Hyperactive), which is built on top of GFO. It provides all optimization algorithms of GFO and expands its capability. You can see how it can handle strings in the search space in [this example](https://github.com/SimonBlanke/Hyperactive/blob/master/examples/optimization_applications/search_space_example.py).
