### ISSUE TITLE
Implement genetic algorithm

### ISSUE THREAD

**Issue by igaloly** [SimonBlanke/Gradient-Free-Optimizers#46]
What do you think about implementing more EA algorithms from DEAP

![image](https://github.com/SimonBlanke/Gradient-Free-Optimizers/assets/38460810/68ea84e9-c709-47e6-a0a8-8b84866d2ce1)

**Comment by SimonBlanke** [comment]
Hello @igaloly,

thank you for the suggestion.

I looked into the package you posted. It turns out, that DEAP is the basis for [Tpot](https://github.com/EpistasisLab/tpot), which inspired me to create my own package for optimization.

Some of the algorithms in the DEAP package are not fit to be implemented in GFO (because they require a continuous search-space). But I will look into more of the algorithms within the next weeks. If you have a suggestion for a particular algorithm you can post it here and explain it and why it fits GFO.

**Comment by SimonBlanke** [comment]
After doing some research I further understood the difference between evolution strategies and genetic algorithms. I would like to add a genetic-algorithm-optimizer to GFO and updated to title of this issue accordingly.

**Comment by SimonBlanke** [comment]
I created an [implementation of the genetic-algorithm-optimizer](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/b38da163a845f713e1566fb912372e24299f7182/gradient_free_optimizers/optimizers/pop_opt/genetic_algorithm.py). I will do some further development in the next days, finish the parameter API and add automatic tests. This is how a search-path-gif of the algorithm solving a rastrigin-function looks like:

![GeneticAlgorithmOptimizer_3_1](https://github.com/SimonBlanke/Gradient-Free-Optimizers/assets/20640612/a521ddc7-ccd0-491c-8bc3-cf3792fe9f32)

**Comment by SimonBlanke** [comment]
I also added the differential evolution algorithm to the sample branch. Also see SimonBlanke/Gradient-Free-Optimizers#48. Now I will refactor the new code. Since GFO has 3 different evolutionary algorithms I would like to use a EvolutionaryAlgorithm-superclass for common-methods and attributes.

**Comment by SimonBlanke** [comment]
This feature was released (today) in v1.5.0
